{"version":3,"sources":["index.ts"],"names":[],"mappings":";;;;;AAAA,kDAA4B;AAC5B,gBAAM,CAAC,MAAM,EAAE,CAAC;AAChB,6BAA0B;AAE1B,IAAM,GAAG,GAAG,IAAI,SAAG,EAAE,CAAC,GAAG,CAAC;AAC1B,IAAM,IAAI,GAAG,OAAO,CAAC,GAAG,CAAC,IAAI,IAAI,IAAI,CAAC;AAEtC,GAAG,CAAC,MAAM,CAAC,IAAI,EAAE,UAAC,GAAQ;IACtB,IAAI,GAAG,EAAE;QACL,OAAO,OAAO,CAAC,KAAK,CAAC,GAAG,CAAC,CAAC;KAC7B;IACD,OAAO,OAAO,CAAC,GAAG,CAAC,mCAAmC,EAAE,IAAI,CAAC,CAAC;AAClE,CAAC,CAAC,CAAC;AAEH,OAAO,CAAC,EAAE,CAAC,mBAAmB,EAAE,UAAC,GAAG;IAChC,iDAAiD;IACjD,OAAO,CAAC,KAAK,CAAC,2DAA2D,EAAE,GAAG,CAAC,CAAC;AACpF,CAAC,CAAC,CAAC","file":"index.js","sourcesContent":["import dotenv from 'dotenv';\r\ndotenv.config();\r\nimport {App} from './app';\r\n\r\nconst app = new App().App;\r\nconst port = process.env.PORT || 8080;\r\n\r\napp.listen(port, (err: any) => {\r\n    if (err) {\r\n        return console.error(err);\r\n    }\r\n    return console.log('Application is running on port - ', port);\r\n});\r\n\r\nprocess.on('uncaughtException', (err) => {\r\n    // Handle the error in the code, if this happens.\r\n    console.error('Uncaught Exception occurred while execution, Root cause: ', err);\r\n});\r\n"]}