{"version":3,"sources":["index.ts"],"names":[],"mappings":";;;;;AAAA,kDAA4B;AAC5B,gBAAM,CAAC,MAAM,EAAE,CAAC;AAChB,6BAA0B;AAE1B,IAAM,GAAG,GAAG,IAAI,SAAG,EAAE,CAAC,GAAG,CAAC;AAC1B,IAAM,IAAI,GAAG,IAAI,CAAC;AAElB,GAAG,CAAC,MAAM,CAAC,IAAI,EAAE,UAAC,GAAQ;IACtB,IAAI,GAAG,EAAE;QACL,OAAO,OAAO,CAAC,KAAK,CAAC,GAAG,CAAC,CAAC;KAC7B;IACD,OAAO,OAAO,CAAC,GAAG,CAAC,mCAAmC,EAAE,IAAI,CAAC,CAAC;AAClE,CAAC,CAAC,CAAC;AAEH,OAAO,CAAC,EAAE,CAAC,mBAAmB,EAAE,UAAC,GAAG;IAChC,iDAAiD;IACjD,OAAO,CAAC,KAAK,CAAC,2DAA2D,EAAE,GAAG,CAAC,CAAC;AACpF,CAAC,CAAC,CAAC","file":"../index.js","sourcesContent":["import dotenv from 'dotenv';\ndotenv.config();\nimport {App} from './app';\n\nconst app = new App().App;\nconst port = 4200;\n\napp.listen(port, (err: any) => {\n    if (err) {\n        return console.error(err);\n    }\n    return console.log('Application is running on port - ', port);\n});\n\nprocess.on('uncaughtException', (err) => {\n    // Handle the error in the code, if this happens.\n    console.error('Uncaught Exception occurred while execution, Root cause: ', err);\n});\n"]}